name: Multiple Commands
on:
  push:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands
        run: |
          echo "Starting Job..."
          pwd
          ls
          echo "Completed"
