name: Python Quality Checks

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r github_notification_project/requirements.txt

      - name: Run Flake8
        run: |
          python -m flake8 github_notification_project

      - name: Run Ruff
        run: |
          python -m ruff check github_notification_project

      - name: Run PyTest
        run: |
          python -m pytest github_notification_project/tests