name: Python Example
on:
  push:
jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Python
        run: |
          python -c "print('Hello from python')"
